baseURL: https://blog.networkchallenge.de/ringana-prices/
languageCode: de-de
title: Ringana Data
dataDir: prices
theme: vanilla-bootstrap
timeZone: Europe/Berlin
enableGitInfo: true

menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Produkte
    pre: archive
    url: /produkte/
    weight: 2

params:
  containerMaxWidth: 1024px